name: Internal Merge
on:
  pull_request:
    paths: ["action.yml", ".github/workflows/*.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  call:
    uses: ./.github/workflows/github-actions.yml
    with:
      pull-request: ${{ github.event.pull_request.number }}
    permissions:
      contents: write
      pull-requests: write
