name: Internal Merge
on:
  pull_request:
    paths: [".github/workflows/_internal-*.yml", ".github/workflows/_internal-*.yaml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  call:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]' }}
    uses: ./.github/workflows/github-actions.yml
    with:
      pull-request: ${{ github.event.pull_request.number }}
    permissions:
      contents: write
      pull-requests: write
